# use_frameworks!

platform :ios, '9.0'

target 'LWWebLoader_Example' do
  pod 'LWWebLoader', :path => '../'
  
  pod 'LWWebSocket',:source => 'https://gitee.com/lw_ios_project/mylibrepo.git'
  # pod 'LWWebSocket', :path => '../../LWWebSocket/'

  # pod 'WebViewJavascriptBridge', '~> 6.0.3'

end
